### ISSUE TITLE
Publish checklist

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#310]
Everything that needs to happen for publish

## Code to write

- [x] Finish validation #302
- [x] Delete computed/injected properties from incoming metadata before it is saved in DB
- [x] Use Dorota's DOI publish function
- [x] Migrate all metadata to schema version 0.4.1
  - [x] @satra mentioned he would write a function that takes 0.3.1 compliant metadata and outputs 0.3.2(?)
  - [x] Update computed asset metadata https://github.com/dandi/dandi-api/pull/316#discussion_r647639084
  - [x] We would just take this function and write a django script to apply it to all draft versions
  - [x] Bump the `SCHEMA_VERSION` in https://github.com/dandi/dandi-infrastructure/blob/master/terraform/api.tf#L27
- [x] Merge https://github.com/dandi/dandiarchive/pull/730 into staging ( @mvandenburgh )
- [x] Figure out what's up with dandi-cli testing errors
- [x] Thoroughly test publish in staging
  - [x] The Publish button should only be enabled when version+asset metadata is valid, and should have error messages otherwise
  - [x] Manifest files are written and have the correct content
  - [x] DOIs are generated (and published?) correctly on the test server.
    - [x] @yarikoptic Clarify if publishing on the test server is cool, since it's so very very permanent
  - [x] dandi-cli can pull correctly from published dandisets
  - [x] Everything in the UI still looks acceptable for published dandisets.
- [x] [Do not allow deletes on dandisets with published versions](https://github.com/dandi/dandi-api/issues/288)

## Deploying
- [x] Merge `staging` to `master`
- [x] Run migrate_version_metadata script
- [x] Update schemaVersion in Terraform
- [x] Migrate asset metadata (@yarikoptic, @satra  et al )
- [x] Update DOI server/user to production in https://github.com/dandi/dandi-infrastructure/blob/master/terraform/api.tf#L28-L29
  - [x] Update the DOI password in the Terraform cloud secret variables
- [x] Are we publishing everyone's dandisets for them, or are we letting users deal with that? (We are letting users publish their own dandisets.)
- [x] Investigate Yarik's publishing failure
- [x] Allow users to publish (currently only admins have permission)

**Comment by waxlamp** [comment]
This is great. Let me know how I can help execute.

**Comment by waxlamp** [comment]
Can this be closed?

j/k, j/k, I'm closing it.
